dist: xenial

language: node_js
node_js: "node"
cache:
  directories:
    - "node_modules"

services:
  - mysql

os:
  - linux

before_install:
  - mysql -e 'CREATE DATABASE graphql_server_boilerplate;'

install:
  - npm install
  - npm run server

script:
  - npm run ci
