language: node_js
node_js: "node"
cache:
  directories:
    - "node_modules"

services:
  - mysql

os:
  - windows

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS graphql_server_boilerplate;'

install:
  - npm install
  - npm start
